### ISSUE TITLE
Cannot resolve symbol 'seon'

### ISSUE THREAD

**Issue by trinitiwowka** [seontechnologies/seon-android-sdk-public#20]
Hi! How i can fix it?

import io.seon.androidsdk.service;

<img width="387" alt="image" src="https://github.com/seontechnologies/seon-android-sdk-public/assets/8225740/f81e7644-7ba6-4bf6-9b97-fc367d7f1a23">

**Comment by trinitiwowka** [comment]
And another question: can i use sdk without `.withContext(getApplicationContext())` ? because now i get infinite waiting for function execution( seonFingerprint.getFingerprintBase64)

**Comment by robertorsulics-seon** [comment]
Hey @trinitiwowka ! I'm going to need a bit more context. For example from the `@CapacitorPlugin` annotation I'm assuming you are using [Capacitor](https://capacitorjs.com) ? The `Cannot resolve symbol` message usually means that the SDK has not been properly imported. I'm not familiar how Capacitor JS works but please make sure you have followed the [SDK's documentation](https://github.com/seontechnologies/seon-android-sdk-public#using-gradle) where applicable and the necessary lines are included in your app's `build.gradle` file. 

> And another question: can i use sdk without .withContext(getApplicationContext()) ? because now i get infinite waiting for function execution( seonFingerprint.getFingerprintBase64)


No, passing the application context is required for the SDK to function properly. This infinite waiting time can stem from your first issue, if the SDK isn't properly included in your application. Otherwise if imported successfully, please make sure you use the latest available version. If your issue still occurs then please get back to me with some more details.

R

**Comment by robertorsulics-seon** [comment]
closed due to inactivity

**Comment by trinitiwowka** [comment]
Thank you. my solution was  
`            Seon seonFingerprint = new SeonBuilder()
                    .withContext(this.getActivity().getApplicationContext())
                    .withSessionId(SESSION_ID)
                    .build();`
