### ISSUE TITLE
Invalid package reference - javax.naming.directory

### ISSUE THREAD

**Issue by tyborg** [seontechnologies/seon-android-sdk-public#41]
Hi,

I updated from 6.2.0 to 6.5.0 and I got this error:
/.gradle/caches/transforms-4/f5616b567353cfcabe079da50eadc494/transformed/androidsdk-6.5.0/jars/classes.jar: Error: Invalid package reference in io.seon.androidsdk:androidsdk; not included in Android: javax.naming.directory. Referenced from org.bouncyseoncastle.jce.provider.CrlCache. [InvalidPackage]

Can you help to me to solve it?

**Comment by szabolcsadam-seon** [comment]
Hey @tyborg !

Have you tried to use the solution above yet?

**Comment by tyborg** [comment]
Hi @szabolcsadam-seon ,

Yes, this is a lint error, but I do not want to ignore it because I worry I will get an issue in production.
https://googlesamples.github.io/android-custom-lint-rules/checks/InvalidPackage.md.html

I can share more information or logs with you privately. I tried reaching you via the Customer Success Team, but they have not answered.

**Comment by szabolcsadam-seon** [comment]
Hi @tyborg !

Although this shouldn't cause any production errors in this specific case, I completely understand that you don't want to disable this type of lint errors. The error comes from an unused section of a library we use(targeting another platform), so it cannot cause a runtime error, but the static checkers rightfully mark it as a potential error source. 
In the case of ProGuard, we previously included a rule that overcomes these errors, but in the case of linters, this apparently did not solve the problem. 
In the next release, we will remove the flagged code parts so that the library can pass stricter static checks.

I will update this thread when the next version is released!

**Comment by szabolcsadam-seon** [comment]
Hey @tyborg !

We just released a new version (6.5.1) of our SDK.
In this release, we removed every reference of the problematic `javax.naming` classes, so the lint error you reported should not appear again.

Please get back to me if this solved your issue.
